### ISSUE TITLE
Add Github topics to make repository more discoverable

### ISSUE THREAD

**Issue by MightyKnight** [Devan-Kerman/NanoEvents#2]
Githubs search is really useful if you use topics. To find new fabric libraries, I use `topic:minecraft-fabric topic:library`.
_Using them makes a repository easy to discover and more visible._

You should [add the following topics](https://docs.github.com/en/github/administering-a-repository/classifying-your-repository-with-topics) to your repository (these are the most common in other fabric projects and fit for this):
- minecraft
- minecraft-fabric
- fabricmc
- library

E.g.:
![grafik](https://user-images.githubusercontent.com/38622942/89180425-08ee5500-d592-11ea-8ac4-dc68fb8ba155.png)

This is small change that can be done in less than a minute and it would help future users a lot.
Thank you.

**Comment by Ueaj-Kerman** [comment]
done
